export const COPY = {
  ui: {
    starsAriaLabel: (rating: number) => `${rating} out of 5 stars`,
  },
  search: {
    placeholder: 'Search for restaurant cuisine, chef',
    ariaLabel: 'Search',
    noResults: 'No results found, please try again.',
  },
  site: {
    name: 'Epicure',
    titleTemplate: '%s | Epicure',
    description:
      'Discover the finest restaurant experiences, curated by world-class chefs.',
  },
  header: {
    logoText: 'EPICURE',
    logoAlt: 'Epicure',
    logoAriaLabel: 'Epicure home',
    searchAriaLabel: 'Search',
    profileAriaLabel: 'Profile',
    cartAriaLabel: 'Cart',
  },
  mobileMenu: {
    openAriaLabel: 'Open navigation menu',
    dialogAriaLabel: 'Navigation menu',
    closeAriaLabel: 'Close navigation menu',
    contactUs: 'Contact Us',
    termsOfUse: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
  },
  popularRestaurants: {
    sectionTitle: 'POPULAR RESTAURANT IN EPICURE:',
    ctaText: 'All restaurants',
    ctaArrowAlt: 'View all restaurants',
  },
  signatureDishes: {
    sectionTitle: 'SIGNATURE DISH OF:',
    ctaText: 'All restaurants',
    ctaArrowAlt: 'View all restaurants',
    spicyAlt: 'Spicy',
    vegetarianAlt: 'Vegetarian',
    veganAlt: 'Vegan',
    shekelSign: '₪',
  },
  foodIcons: {
    sectionTitle: 'THE MEANING OF OUR ICONS:',
    spicyLabel: 'Spicy',
    spicyAlt: 'Spicy dish icon',
    vegetarianLabel: 'Vegetarian',
    vegetarianAlt: 'Vegetarian dish icon',
    veganLabel: 'Vegan',
    veganAlt: 'Vegan dish icon',
  },
  chefOfTheWeek: {
    sectionTitle: 'CHEF OF THE WEEK:',
    restaurantsTitle: (firstName: string) => `${firstName}'s restaurants`,
  },
  aboutUs: {
    logoAlt: 'Epicure',
    googleAlt: 'Get it on Google Play',
    appleAlt: 'Download on the App Store',
    title: 'ABOUT US',
    paragraph1:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a lacus vel justo fermentum bibendum non eu ipsum. Cras porta malesuada eros, eget blandit turpis suscipit at. Vestibulum sed massa in magna sodales porta. Vivamus elit urna, dignissim a vestibulum.',
    paragraph2:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a lacus vel justo fermentum bibendum non eu ipsum. Cras porta malesuada eros.',
  },
  chefs: {
    pageTitle: 'CHEFS',
    filterAll: 'All',
    filterNew: 'New',
    filterMostViewed: 'Most Viewed',
    filterAriaLabel: 'Filter chefs',
    emptyAll: 'No chefs available at the moment.',
    emptyNew: 'No new chefs at the moment.',
    emptyMostViewed: 'No featured chefs at the moment.',
    errorMessage: 'Something went wrong loading the chefs.',
    errorRetry: 'Try again',
  },
  restaurants: {
    pageTitle: 'Restaurants',
    filterAll: 'All',
    filterNew: 'New',
    filterMostPopular: 'Most Popular',
    filterOpenNow: 'Open Now',
    filterMapView: 'Map View',
    filterBarPriceRange: 'Price Range',
    filterBarDistance: 'Distance',
    filterBarRating: 'Rating',
    filterBarPriceTitle: 'Price Range Selected',
    filterBarPriceValue: (min: number, max: number) => `₪${min} - ₪${max}`,
    filterBarDistanceTitle: 'Distance',
    filterBarDistanceValue: (km: number) => `${km} km`,
    filterBarMyLocation: 'My Location',
    filterBarRatingTitle: 'Rating',
    filterBarLocating: 'Locating…',
    filterBarEnterAddress: 'Enter address manually',
    filterBarTryGps: 'Use my location instead',
    filterBarDistanceAriaLabel: 'Maximum distance in km',
    filterBarAddressPlaceholder: 'Enter an address in Tel Aviv',
    filterBarAddressSubmit: 'Search',
    filterBarAddressSearching: 'Searching address…',
    filterBarAddressError:
      'Address not found or not in Tel Aviv. Please try again.',
    errorMessage: 'Something went wrong loading the restaurants.',
    errorRetry: 'Try again',
    openNowEmpty: 'No restaurants are currently open. Please come back soon!',
  },
  cuisine: {
    empty: 'No restaurants available for this cuisine at the moment.',
  },
  chefDetail: {
    restaurantsTitle: (firstName: string) => `${firstName}'s restaurants`,
    noRestaurants: 'No restaurants listed for this chef.',
  },
  auth: {
    closeAriaLabel: 'Close sign in',
    signInTitle: 'Sign in',
    signInSubtitle: 'To continue the order, please sign in',
    signUpTitle: 'Sign up',
    namePlaceholder: 'Name',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    confirmPasswordPlaceholder: 'Confirm password',
    loginButton: 'Login',
    forgotPassword: 'Forgot password?',
    or: 'or',
    signUpButton: 'Sign up',
    showPasswordAriaLabel: 'Show password',
    hidePasswordAriaLabel: 'Hide password',
    loginError: 'Email or password is incorrect. Please try again.',
    signUpError: 'Please check your details and try again.',
    nameRequiredError: 'Please enter your name.',
    invalidEmailError: 'Please enter a valid email address.',
    passwordRequirementsError:
      'Password must be 8-64 characters, with at least one uppercase letter and one special character.',
    passwordMismatchError: 'Passwords do not match.',
    emailInUseError: 'An account with this email already exists.',
    genericError: 'Something went wrong. Please try again.',
    helloName: (name: string) => `Hello, ${name}!`,
    signOutLabel: 'Log out',
  },
  cart: {
    title: 'My order',
    desktopTitle: 'Your order',
    closeAriaLabel: 'Close cart',
    totalLabel: 'Total',
    checkoutAlt: 'Checkout',
    checkoutLabel: (total: number) => `Checkout ₪${total}`,
    orderHistoryLabel: 'Order history',
    cartAriaLabel: (count: number) => `Cart, ${count} items`,
    emptyLine1: 'Your bag is',
    emptyLine2: 'empty',
    desktopEmptyLine1: 'Your bag',
    desktopEmptyLine2: 'is empty',
    addCommentTitle: 'Add a comment',
    commentPlaceholder:
      'Special requests, allergies, dietary restrictions, etc.',
    unitPrice: (price: number) => `₪${price.toFixed(2)}`,
  },
  dishDetail: {
    closeAriaLabel: 'Close dish details',
    chooseASideTitle: 'Choose a side',
    sideOptions: ['White bread', 'Sticky rice'],
    changesTitle: 'Changes',
    changeOptions: ['Without peanuts', 'Less spicy'],
    quantityTitle: 'Quantity',
    decreaseAriaLabel: 'Decrease quantity',
    increaseAriaLabel: 'Increase quantity',
    addToBagAlt: 'Add to bag',
    shekelSign: '₪',
  },
  restaurantDetail: {
    openNow: 'Open now',
    closedNow: 'Closed now',
    breakfastTab: 'Breakfast',
    lunchTab: 'Lunch',
    dinnerTab: 'Dinner',
    clockAlt: 'Clock icon',
    noImage: 'Restaurant image',
    noDishes: (meal: string) =>
      `No dishes available for ${meal.charAt(0).toUpperCase()}${meal.slice(1)}`,
  },
} as const;
