name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules to speed up npm install
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Check formatting
      - run: npx nx format:check --base="remotes/origin/main"

      # Run your core tasks locally on the GitHub runner (Changed e2e-ci to e2e)
      - run: npx nx run-many -t lint test build typecheck e2e